### ISSUE TITLE
In order to test the method of organizing existing content, prototype the process based on one document. 

### ISSUE THREAD

**Issue by jenniferthibault** [18F/cic-site#17]
In order to identify the most useful parts of the content we have (and need) for the first round, 
separate documents down into constituent parts. 

Demonstrate approach through one document as an example to create team-wide buy in for the approach, and to start informing the building blocks within the future IA. These building blocks will help us prepare to card sort an IA with users.

This task will be complete when we have:

- [x] Identified one area and created an example.
- [x] Skimmed, prioritized, and culled down content. 
- [x] Demonstrated this work to the project team
- [x] Learned how long this process takes so we know what the return on the investment for doing more of it would be.

**Comment by jenniferthibault** [comment]
@abbeykos Can you please add the resources here & say more about what the path out of "Accepting" looks like?

**Comment by jenniferthibault** [comment]
Nudge @abbeykos 👋 ☝️

**Comment by abbeykos** [comment]
Link to presentation https://docs.google.com/presentation/d/1GkLb5WvXhqKxQEIBVRPSr9HOhPQNmtp3ZdoI5a4pxSA/edit
