### ISSUE TITLE
In order to flesh out the components of the site architecture, complete the first half of the content organization

### ISSUE THREAD

**Issue by jenniferthibault** [18F/cic-site#18]
Complete the process demonstrated in #17  with the total known documents (~20 of varying lengths) to get a first sense of the content components available. We'll break down this content work into two parts.

To complete the first part:
- [x] Cross reference the content list with Colin, CIC team to make sure we've identified the full list of content
- [x] Create a list of the documents that we need to get through 
- [x] Create a list of subject areas to split content into
- [x] Outline the content building blocks through the process in #17

**Comment by abbeykos** [comment]
Subject areas to split content into:
* Assessment
* ATO
* Basics
* Benefits
* Business case
* Change
* cloud.gov
* Containers
* Devops/Lean/Agile
* IaaS/PaaS/SaaS
* Pricing
* Process
* Reporting
* Research
* Resources
* Security
* Strategy
* Templates
* Vendors
