### ISSUE TITLE
Onboard Jennifer to CIC project

### ISSUE THREAD

**Issue by jenniferthibault** [18F/cic-site#21]
So that Jennifer can get up to speed with project context and contribute to the product vision, we should help her know where to start.

Important project documents & history:
- [x] [Project SOW](https://docs.google.com/document/d/1VnCZ1wLJbnwgJvPUPqHmrsfPjLwkQrdSdp8rAFo3fVw/edit)
- [x] Read through the [Kick off deck & accompanying notes](https://drive.google.com/drive/u/0/folders/1XxDXZRw5nEd134fjncMeuZGTQFZQ4WNX)
- [x] Get acquainted with the [story map](https://app.mural.co/invitation/mural/gsa6/1533622577595?sender=bretmogilefsky&key=f26d46a8-6fbf-4fe7-83c9-6f50878490e5)
- [x] [User research notes](https://drive.google.com/drive/u/0/folders/1CjIeYiFQwwFSAnDtmrI1SBVnlV-t6eKJ) & [research synthesis](https://docs.google.com/presentation/d/10e2l0qXcyB3OSklEZKQAgB86H9H37jRBpbaOzi2r4Mw/edit#slide=id.g3cd3cfdefd_0_178)
- [x] The full [google drive folder](https://drive.google.com/drive/u/0/folders/19NozbUFBkp99SBrIDAkzW-S0ZVZepL3u)

Resources for cloud context:
- [x] Intros to cloud from [Amazon](https://aws.amazon.com/what-is-cloud-computing/) & [Microsoft](https://azure.microsoft.com/en-us/overview/what-is-cloud-computing/)
- [x] [Something] as a Service models ( _aaS ): meet the [Pizza as a Service](https://medium.com/@pkerrison/pizza-as-a-service-2-0-5085cd4c365e) analogy 
- [x] [Slides 35-45](https://docs.google.com/presentation/d/1BoxFeENJcINgHbKfygXpXROchiRO2LBT-pzdaOFr4Zg/edit#slide=id.g39c264972c_182_1000): a brief outline on the evolution of cloud computing
- [ ] [Cloud Infrastructure in the Federal Government](https://www.navapbc.com/uploads/nava-dora-federal-cloud-infrastructure-whitepaper.pdf) A deeper primer: this whitepaper is more specific to our context , ~ 30 pgs but it's pretty spaciously set, the body copy is only half page-width

Resources for GitHub
- [ ] [TTS Intro to GitHub](https://handbook.18f.gov/intro-to-github/) Check out the links to Will Slack's GitHub for beginners course at the top.
- [ ] [How to use GitHub and the terminal: a guide](https://18f.gsa.gov/2015/03/03/how-to-use-github-and-the-terminal-a-guide/), 18F blog. This one is more oriented toward folks who want to work in the terminal, but don't let that stop you, it sets up good intros to vocab and concepts that your engineering team members will be using. 
- [ ] [Intro to version control](https://www.webdesignerdepot.com/2009/03/intro-to-git-for-web-designers/) (Stop reading when you hit "Meet Git" if you want — that's the programming language and you don't _need_ to know it for our purposes)

Tools:
- [x] Mural.ly account
- [x] Sketch
- [x] InVision for prototyping
- [x] Zenhub / GitHub proper permissions
- [x] Jive

**Comment by jenniferthibault** [comment]
@jdamis4XD  could you please check off what you’ve done so far on this issue so it's up to date? That'll help me know where we should focus in our 1:1 this afternoon.

**Comment by jdamis4XD** [comment]
Done.  I didn't realize this was a task of mine also or I would have updated yesterday.

**Comment by jenniferthibault** [comment]
@jdamis4XD since the remaining tasks are optional, and doesn't sound like it's been top-of-agenda in standups, can we close this ticket?
