### ISSUE TITLE
Define priority tasks for each user type

### ISSUE THREAD

**Issue by jenniferthibault** [18F/cic-site#26]
In order to understand what core features we should prioritize building (and make sure we're building the right thing), we need to understand and define what main tasks each user segment needs to accomplish through this site/tool.

We'll use these tasks in usability testing to validate the success of features as we build them.

This task will be complete when:
- [x] A list of personas or user types exists
- [x] Each persona has a minimum set of needs/tasks to accomplish
- [x] We've called out any gaps in our knowledge

**Comment by jdamis4XD** [comment]
Personas and Top tasks: https://docs.google.com/spreadsheets/d/1BqFjs_9ctwuRQr3oCoHrVDAzIDfs4Pb9sdof-Oe9KYg/edit?usp=sharing
