### ISSUE TITLE
Test & validate user needs and tasks by usability testing prototype on Federalist site

### ISSUE THREAD

**Issue by jenniferthibault** [18F/cic-site#27]
Use a prototype to understand and validate feature sets and interactions so that we have a more updated sense of priority features and tasks.

This task will be complete when we've:
- [x] Identify how many people in each user segment we want to usability test with
- [x] Create the interview/testing script
- [x] Usability tests have been scheduled
- [x] Usability tests have been conducted
- [x] Usability tests have been synthesized into findings that tell us what features are critical to MVP
- [x] Define how to update the team or read out what we've learned
- [x] Add links to script / prototypes / findings to this issue

**Comment by jdamis4XD** [comment]
Research plan and test script: https://docs.google.com/document/d/1o6Nt7iv6pbat-DxSN8pCNtfQv1L7ThL8tSkb9901O5g/edit?usp=sharing

**Comment by jdamis4XD** [comment]
Federalist prototype: https://federalist-proxy.app.cloud.gov/preview/18f/cic-site/implement-sitemap-content/

**Comment by jdamis4XD** [comment]
Test participants: https://docs.google.com/spreadsheets/d/1xRk87Z0PoyQ-BBjWfVDxGdox3SYAGcme2grKHxrviPU/edit?usp=sharing

**Comment by jdamis4XD** [comment]
Synthesized observation findings: https://docs.google.com/spreadsheets/d/129nY8hOI-MCln6yr56sCz9SBVjrX3X812Gxn1bO6qpw/edit?usp=sharing

Final presentation: https://drive.google.com/open?id=1Yf30XnZH7SN2FCwSBHPPRgEendkhbaYqFBQO5eZWvgc
