### ISSUE TITLE
Set up mail aliases for use in calendar

### ISSUE THREAD

**Issue by mogul** [18F/cic-site#3]
In order to ensure continuity as the people involved in the project change, we want to use groups to represent the set of people who should attend recurring events.

ACs
- [ ] There are appropriate Google Groups for the set of people who are running and attending meetings, populated with the people we know about based on our best guess from the RACI sheet.

**Comment by jenniferthibault** [comment]
I didn't end up using this approach for this round, but may change that in the future. Closing —
