### ISSUE TITLE
Wireframe Developments

### ISSUE THREAD

**Issue by jdamis4XD** [18F/cic-site#31]
Need to create  a low fi prototype for Usability testing to help us identify user tasks and content needs for cloud products.

- [x] Create wireframe templates for content structure

- [x] Create a sitemap

**Comment by jdamis4XD** [comment]
Wireframes: https://drive.google.com/open?id=17Tu2SpxTUQZ04zoRhcDUoUhuq6SpTlcN

Sitemap: https://drive.google.com/open?id=1iLz-Yoe0perVmGmgx3qJlHiV9_hwEZPJ

**Comment by jdamis4XD** [comment]
We decided to have Laura build the prototype in Federalist, so I am going to remove the second check item.

**Comment by jenniferthibault** [comment]
This looks completed from the criteria above. Is this issue ok to close @jdamis4XD or would you prefer to make any new follow-up issues before closing?
