### ISSUE TITLE
Why cloud - Security and compliance: As a govt user, I want to learn about non-technical impact/benefits so that I can make a better case

### ISSUE THREAD

**Issue by jenniferthibault** [18F/cic-site#57]
- [x] content drafted
- [x] content reviewed
- [x] content updated
- [x] content on site
- [x] layout updated
- [x] nav updated

**Comment by abbeykos** [comment]
1.4 Security and compliance has been reviewed, updated, and is ready to go on the site

**Comment by jenniferthibault** [comment]
Added via #128
