### ISSUE TITLE
Set up analytics on CIC site

### ISSUE THREAD

**Issue by mogul** [18F/cic-site#9]
In order to understand how users are traversing the CIC site at each stage of its development, we want the site to log visitor info to Google Analytics.

*Acceptance Criteria*
- [x] There's a dedicated Google Analytics entry for the CIC site
- [x] Appropriate people on the project have access to the Google Analytics data
- [x] Visits to the CIC site show up in Google Analytics reports 

---
This involves talking to the DAP folks to get an ID for this site/project, and then making sure it appears in the Federalist template in the right place.

**Comment by jenniferthibault** [comment]
Pairing with a member of the DAP team tomorrow to set up an instance using Google Tag Manager so that we can have more visibility into user behavior
